USE [Esign_new]
GO
SET ANSI_PADDING ON
GO

/****** Object:  Index [CustomerID_Query]    Script Date: 30/12/2024 14:59:05 ******/
CREATE NONCLUSTERED INDEX [CustomerID_Query] ON [dbo].[certificates]
(
	[customerid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [Company_OrderBy]    Script Date: 30/12/2024 15:00:19 ******/
CREATE NONCLUSTERED INDEX [Company_OrderBy] ON [dbo].[certificates]
(
	[company] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [Hpnumber_OrderBy]    Script Date: 30/12/2024 15:00:56 ******/
CREATE NONCLUSTERED INDEX [Hpnumber_OrderBy] ON [dbo].[certificates]
(
	[hpnumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
