// <auto-generated />
using System;
using EsignBackend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsignBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1255_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EsignBackend.Models.Attachment", b =>
                {
                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("File1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("file1")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double?>("Ticketid")
                        .HasColumnType("float")
                        .HasColumnName("ticketid");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Budesign", b =>
                {
                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Fieldname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fieldname")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("File1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("file1")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Lable")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lable")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Value1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("value1")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.ToTable("budesign", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Bulanguage", b =>
                {
                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<double?>("Entityid")
                        .HasColumnType("float")
                        .HasColumnName("entityid");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double?>("Parentid")
                        .HasColumnType("float")
                        .HasColumnName("parentid");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.ToTable("bulanguages", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Bumodule", b =>
                {
                    b.Property<string>("Addcsv")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("addcsv")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Addduplicatebutton")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("addduplicatebutton")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Addloadcsv")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("addloadcsv")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Addmultiactions")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("addmultiactions")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Addnav")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("addnav")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Addpages")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("addpages")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Addprint")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("addprint")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Addsearch")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("addsearch")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Addsearchbar")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("addsearchbar")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Addtrans")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("addtrans")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Astree")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("astree")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Created")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("created")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Createtable")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("createtable")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Defaultorder")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("defaultorder")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Display")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("display")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Icon")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("icon")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Monthviewfield")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("monthviewfield")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Multilang")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("multilang")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Navgrouptitle")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("navgrouptitle")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Permissions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("permissions")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<string>("Showid")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("showid")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime?>("Updateddate")
                        .HasColumnType("datetime")
                        .HasColumnName("updateddate");

                    b.Property<double?>("Updateduserid")
                        .HasColumnType("float")
                        .HasColumnName("updateduserid");

                    b.ToTable("bumodules", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Bumodulecoderep", b =>
                {
                    b.Property<string>("Applytoall")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("applytoall")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double?>("Parentid")
                        .HasColumnType("float")
                        .HasColumnName("parentid");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Text1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text1")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Text2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text2")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<double?>("Tid")
                        .HasColumnType("float")
                        .HasColumnName("tid");

                    b.Property<double?>("Times")
                        .HasColumnType("float")
                        .HasColumnName("times");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.ToTable("bumodulecoderep", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Bumodulefield", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Tcontrol")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tcontrol")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Tdata")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tdata")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Tdefault")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tdefault")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Tdir")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tdir")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Tdisplay")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tdisplay")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Tfilter")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("tfilter")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Thelp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thelp")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<double?>("Tid")
                        .HasColumnType("float")
                        .HasColumnName("tid");

                    b.Property<double?>("Tlength")
                        .HasColumnType("float")
                        .HasColumnName("tlength");

                    b.Property<string>("Tlist")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("tlist")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Tlistupdate")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("tlistupdate")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<double?>("Tmax")
                        .HasColumnType("float")
                        .HasColumnName("tmax");

                    b.Property<double?>("Tmin")
                        .HasColumnType("float")
                        .HasColumnName("tmin");

                    b.Property<string>("Tmultiupdate")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("tmultiupdate")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Tmust")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("tmust")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Tname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tname")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Tnotr")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("tnotr")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<double?>("Tpriority")
                        .HasColumnType("float")
                        .HasColumnName("tpriority");

                    b.Property<string>("Ttype")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ttype")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.ToTable("bumodulefields", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Busetting", b =>
                {
                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Explain1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("explain1")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("Parentid")
                        .HasColumnType("int")
                        .HasColumnName("parentid");

                    b.Property<double?>("Priority")
                        .HasColumnType("float")
                        .HasColumnName("priority");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.ToTable("busettings", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Buuser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allowedips")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("allowedips")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Departmantid")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("departmantid")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<double?>("Elang")
                        .HasColumnType("float")
                        .HasColumnName("elang");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime?>("Expires")
                        .HasColumnType("datetime")
                        .HasColumnName("expires");

                    b.Property<string>("Firstname")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("firstname")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Lastname")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("lastname")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<double?>("Parentid")
                        .HasColumnType("float")
                        .HasColumnName("parentid");

                    b.Property<string>("Pass")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("pass")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Permissions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("permissions")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Picture")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("picture")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<double?>("Provider")
                        .HasColumnType("float")
                        .HasColumnName("provider");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarks")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Sessionvalues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sessionvalues")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime?>("Updateddate")
                        .HasColumnType("datetime")
                        .HasColumnName("updateddate");

                    b.Property<double?>("Updateduserid")
                        .HasColumnType("float")
                        .HasColumnName("updateduserid");

                    b.Property<string>("Usergroup")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("usergroup")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Userlevel")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("userlevel")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Username")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("username")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("buusers", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Callpriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("callpriority", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Callstatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("callstatus", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttorneyLicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CertificateissuerId")
                        .HasColumnType("int")
                        .HasColumnName("certificateissuerid");

                    b.Property<int?>("CertificatestatusId")
                        .HasColumnType("int")
                        .HasColumnName("certificatestatusid");

                    b.Property<string>("Company")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("company");

                    b.Property<int?>("Customerid")
                        .HasColumnType("int")
                        .HasColumnName("customerid");

                    b.Property<int?>("DocstypeId")
                        .HasColumnType("int")
                        .HasColumnName("docstypeid");

                    b.Property<string>("Email")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("email");

                    b.Property<int?>("Expire")
                        .HasColumnType("int")
                        .HasColumnName("expire");

                    b.Property<DateTime?>("Expiredate")
                        .HasColumnType("datetime")
                        .HasColumnName("expiredate");

                    b.Property<string>("Hotem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hotem");

                    b.Property<string>("Hpnumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hpnumber");

                    b.Property<int?>("Identify")
                        .HasColumnType("int")
                        .HasColumnName("identify");

                    b.Property<DateTime?>("Issuedate")
                        .HasColumnType("datetime")
                        .HasColumnName("issuedate");

                    b.Property<int?>("IssuerplaceId")
                        .HasColumnType("int")
                        .HasColumnName("issuerplaceid");

                    b.Property<string>("Job")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("job");

                    b.Property<string>("Licenceid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("licenceid");

                    b.Property<string>("Passportid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("passportid");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("projectid");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarks")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Remarksdesc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarksdesc");

                    b.Property<string>("Securityansware")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("securityansware");

                    b.Property<int?>("SecurityquestionId")
                        .HasColumnType("int")
                        .HasColumnName("securityquestionid");

                    b.Property<int?>("SmartobjectId")
                        .HasColumnType("int")
                        .HasColumnName("smartobjectid");

                    b.Property<int?>("SubprojectId")
                        .HasColumnType("int")
                        .HasColumnName("subprojectid");

                    b.HasKey("Id");

                    b.HasIndex("CertificateissuerId");

                    b.HasIndex("CertificatestatusId");

                    b.HasIndex("Customerid");

                    b.HasIndex("DocstypeId");

                    b.HasIndex("Expire");

                    b.HasIndex("Identify");

                    b.HasIndex("IssuerplaceId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SecurityquestionId");

                    b.HasIndex("SmartobjectId");

                    b.HasIndex("SubprojectId");

                    b.ToTable("certificates", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Certificatermeark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("certificatermearks", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Certificateshistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CertificateId")
                        .HasColumnType("int")
                        .HasColumnName("certificateid");

                    b.Property<int?>("CertificateissuerId")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("certificateissuerid");

                    b.Property<int>("CertificatestatusId")
                        .HasColumnType("int")
                        .HasColumnName("certificatestatusid");

                    b.Property<string>("Company")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("company")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerid");

                    b.Property<int?>("DocstypeId")
                        .HasColumnType("int")
                        .HasColumnName("docstypeid");

                    b.Property<string>("Email")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("email")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("Expire")
                        .HasColumnType("int")
                        .HasColumnName("expire");

                    b.Property<DateTime?>("Expiredate")
                        .HasColumnType("datetime")
                        .HasColumnName("expiredate");

                    b.Property<string>("Hotem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hotem")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Hpnumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hpnumber")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Identify")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("identify")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime?>("Issuedate")
                        .HasColumnType("datetime")
                        .HasColumnName("issuedate");

                    b.Property<int?>("IssuerplaceId")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("issuerplaceid");

                    b.Property<string>("Licenceid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("licenceid")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Passportid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("passportid")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("projectid");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarks")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Remarksdesc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarksdesc")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Securityansware")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("securityansware")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("SecurityquestionId")
                        .HasColumnType("int")
                        .HasColumnName("securityquestionid");

                    b.Property<int?>("SmartobjectId")
                        .HasColumnType("int");

                    b.Property<int>("SubprojectId")
                        .HasColumnType("int")
                        .HasColumnName("subprojectid");

                    b.Property<DateTime?>("Updateddate")
                        .HasColumnType("datetime")
                        .HasColumnName("updateddate");

                    b.Property<int?>("UpdateduserId")
                        .HasColumnType("int")
                        .HasColumnName("updateduserid");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("CertificatestatusId");

                    b.HasIndex("DocstypeId");

                    b.HasIndex("Expire");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SecurityquestionId");

                    b.HasIndex("SmartobjectId");

                    b.HasIndex("SubprojectId");

                    b.HasIndex("UpdateduserId");

                    b.ToTable("certificateshistory", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Certificatesstatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("certificatesstatus", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Custident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Active")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("active")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("custident", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<double?>("Calleruserid")
                        .HasColumnType("float")
                        .HasColumnName("calleruserid");

                    b.Property<string>("Certificates")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("certificates")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Company")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("company")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Email")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("email")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Firstname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("firstname");

                    b.Property<string>("Idnumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("idnumber")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Lastname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lastname")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Mobile1")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("mobile1")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Phone1")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone1")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Securityansware")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("securityansware")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("Securityquestion")
                        .HasColumnType("int")
                        .HasColumnName("securityquestionid");

                    b.Property<string>("Temp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("temp")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("Securityquestion");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Departmant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("departmants", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Docstype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("docstype", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Expirationtype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("expirationtype", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Isscert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Active")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("active")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("isscert", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Issplace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Active")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("active")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("issplace", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Progressreport", b =>
                {
                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double?>("Ticketid")
                        .HasColumnType("float")
                        .HasColumnName("ticketid");

                    b.Property<DateTime?>("Updateddate")
                        .HasColumnType("datetime")
                        .HasColumnName("updateddate");

                    b.Property<double?>("Updateduserid")
                        .HasColumnType("float")
                        .HasColumnName("updateduserid");

                    b.ToTable("progressreport", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Securityquestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("securityquestions", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Smartobject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("smartobjects", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Subproject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("projectid");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("subproject", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Ticket", b =>
                {
                    b.Property<double?>("Calleruserid")
                        .HasColumnType("float")
                        .HasColumnName("calleruserid");

                    b.Property<string>("Closerequest")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("closerequest")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Comefrom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("comefrom")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<double?>("Departmantid")
                        .HasColumnType("float")
                        .HasColumnName("departmantid");

                    b.Property<DateTime?>("Donedate")
                        .HasColumnType("datetime")
                        .HasColumnName("donedate");

                    b.Property<DateTime?>("Duedate")
                        .HasColumnType("datetime")
                        .HasColumnName("duedate");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Lastdescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lastdescription")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<double?>("Lastupdater")
                        .HasColumnType("float")
                        .HasColumnName("lastupdater");

                    b.Property<double?>("Priorityd")
                        .HasColumnType("float")
                        .HasColumnName("priorityd");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("projectid");

                    b.Property<DateTime?>("Schedule")
                        .HasColumnType("datetime")
                        .HasColumnName("schedule");

                    b.Property<double?>("Status")
                        .HasColumnType("float")
                        .HasColumnName("status");

                    b.Property<string>("Sulution")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sulution")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Ticketname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ticketname")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<double?>("Transferto")
                        .HasColumnType("float")
                        .HasColumnName("transferto");

                    b.Property<DateTime?>("Updateddate")
                        .HasColumnType("datetime")
                        .HasColumnName("updateddate");

                    b.Property<double?>("Updateduserid")
                        .HasColumnType("float")
                        .HasColumnName("updateduserid");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Userview", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Sessionvalues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sessionvalues")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("Userid")
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    b.ToTable("userviews", (string)null);
                });

            modelBuilder.Entity("EsignBackend.Models.Certificate", b =>
                {
                    b.HasOne("EsignBackend.Models.Isscert", "RelatedCertificateissuer")
                        .WithMany("Certificates")
                        .HasForeignKey("CertificateissuerId");

                    b.HasOne("EsignBackend.Models.Certificatesstatus", "RelatedCertificatesstatus")
                        .WithMany("Certificates")
                        .HasForeignKey("CertificatestatusId");

                    b.HasOne("EsignBackend.Models.Customer", "RelatedCustomer")
                        .WithMany("CustomerCertificates")
                        .HasForeignKey("Customerid");

                    b.HasOne("EsignBackend.Models.Docstype", "RelatedDocsType")
                        .WithMany("Certificates")
                        .HasForeignKey("DocstypeId");

                    b.HasOne("EsignBackend.Models.Expirationtype", "RelatedExpiration")
                        .WithMany("Certificates")
                        .HasForeignKey("Expire");

                    b.HasOne("EsignBackend.Models.Custident", "RelatedCustomerIdentifier")
                        .WithMany("Certificates")
                        .HasForeignKey("Identify");

                    b.HasOne("EsignBackend.Models.Issplace", "RelatedIssuerPlace")
                        .WithMany("Certificates")
                        .HasForeignKey("IssuerplaceId");

                    b.HasOne("EsignBackend.Models.Project", "RelatedProject")
                        .WithMany("Certificates")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsignBackend.Models.Securityquestion", "RelatedSecurityquestion")
                        .WithMany("Certificates")
                        .HasForeignKey("SecurityquestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EsignBackend.Models.Smartobject", "RelatedSmartObject")
                        .WithMany("Certificates")
                        .HasForeignKey("SmartobjectId");

                    b.HasOne("EsignBackend.Models.Subproject", "RelatedSubProject")
                        .WithMany("Certificates")
                        .HasForeignKey("SubprojectId");

                    b.Navigation("RelatedCertificateissuer");

                    b.Navigation("RelatedCertificatesstatus");

                    b.Navigation("RelatedCustomer");

                    b.Navigation("RelatedCustomerIdentifier");

                    b.Navigation("RelatedDocsType");

                    b.Navigation("RelatedExpiration");

                    b.Navigation("RelatedIssuerPlace");

                    b.Navigation("RelatedProject");

                    b.Navigation("RelatedSecurityquestion");

                    b.Navigation("RelatedSmartObject");

                    b.Navigation("RelatedSubProject");
                });

            modelBuilder.Entity("EsignBackend.Models.Certificateshistory", b =>
                {
                    b.HasOne("EsignBackend.Models.Certificate", "RelatedCertificate")
                        .WithMany("HistoryCertificates")
                        .HasForeignKey("CertificateId");

                    b.HasOne("EsignBackend.Models.Certificatesstatus", "RelatedCertificateStatus")
                        .WithMany("HistoryCertificates")
                        .HasForeignKey("CertificatestatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsignBackend.Models.Docstype", "RelatedDocsType")
                        .WithMany("HistoryCertificates")
                        .HasForeignKey("DocstypeId");

                    b.HasOne("EsignBackend.Models.Expirationtype", "RelatedExpiration")
                        .WithMany("HistoryCertificates")
                        .HasForeignKey("Expire");

                    b.HasOne("EsignBackend.Models.Project", "RelatedProject")
                        .WithMany("HistoryCertificates")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsignBackend.Models.Securityquestion", "RelatedSecurityQuestion")
                        .WithMany("HistoryCertificates")
                        .HasForeignKey("SecurityquestionId");

                    b.HasOne("EsignBackend.Models.Smartobject", "RelatedSmartObject")
                        .WithMany("HistoryCertificates")
                        .HasForeignKey("SmartobjectId");

                    b.HasOne("EsignBackend.Models.Subproject", "RelatedSubProject")
                        .WithMany("HistoryCertificates")
                        .HasForeignKey("SubprojectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EsignBackend.Models.Buuser", "RelatedUser")
                        .WithMany("HistoryCertificates")
                        .HasForeignKey("UpdateduserId");

                    b.HasOne("EsignBackend.Models.Customer", "RelatedCustomer")
                        .WithMany("CustomerHistoryCertificates")
                        .HasForeignKey("UpdateduserId");

                    b.Navigation("RelatedCertificate");

                    b.Navigation("RelatedCertificateStatus");

                    b.Navigation("RelatedCustomer");

                    b.Navigation("RelatedDocsType");

                    b.Navigation("RelatedExpiration");

                    b.Navigation("RelatedProject");

                    b.Navigation("RelatedSecurityQuestion");

                    b.Navigation("RelatedSmartObject");

                    b.Navigation("RelatedSubProject");

                    b.Navigation("RelatedUser");
                });

            modelBuilder.Entity("EsignBackend.Models.Customer", b =>
                {
                    b.HasOne("EsignBackend.Models.Securityquestion", "RelatedSecurityquestion")
                        .WithMany("Customers")
                        .HasForeignKey("Securityquestion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RelatedSecurityquestion");
                });

            modelBuilder.Entity("EsignBackend.Models.Subproject", b =>
                {
                    b.HasOne("EsignBackend.Models.Project", "RelatedProject")
                        .WithMany("Subprojects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedProject");
                });

            modelBuilder.Entity("EsignBackend.Models.Buuser", b =>
                {
                    b.Navigation("HistoryCertificates");
                });

            modelBuilder.Entity("EsignBackend.Models.Certificate", b =>
                {
                    b.Navigation("HistoryCertificates");
                });

            modelBuilder.Entity("EsignBackend.Models.Certificatesstatus", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("HistoryCertificates");
                });

            modelBuilder.Entity("EsignBackend.Models.Custident", b =>
                {
                    b.Navigation("Certificates");
                });

            modelBuilder.Entity("EsignBackend.Models.Customer", b =>
                {
                    b.Navigation("CustomerCertificates");

                    b.Navigation("CustomerHistoryCertificates");
                });

            modelBuilder.Entity("EsignBackend.Models.Docstype", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("HistoryCertificates");
                });

            modelBuilder.Entity("EsignBackend.Models.Expirationtype", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("HistoryCertificates");
                });

            modelBuilder.Entity("EsignBackend.Models.Isscert", b =>
                {
                    b.Navigation("Certificates");
                });

            modelBuilder.Entity("EsignBackend.Models.Issplace", b =>
                {
                    b.Navigation("Certificates");
                });

            modelBuilder.Entity("EsignBackend.Models.Project", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("HistoryCertificates");

                    b.Navigation("Subprojects");
                });

            modelBuilder.Entity("EsignBackend.Models.Securityquestion", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Customers");

                    b.Navigation("HistoryCertificates");
                });

            modelBuilder.Entity("EsignBackend.Models.Smartobject", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("HistoryCertificates");
                });

            modelBuilder.Entity("EsignBackend.Models.Subproject", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("HistoryCertificates");
                });
#pragma warning restore 612, 618
        }
    }
}
